export const Prueba = [
  {
    product_name: "Campeonate departamental",
    price: 127.64,
    quantity: 972,
    category: "Campeonato",
    weight: 60.52,
    descripcion:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    id: 1,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROO7fJGwXokRbUj6w4APjPaJsyvhp8Gcvgog&s",
    fecha: "2024-08-23",
    titulo: "EVENTO BENEFICO",
    contenido: "lorem ",
    cargo: "Admin",
    nombre: "pepe",
    rol:"deportista",
  },
  {
    product_name: "Evento regional",
    price: 207.43,
    quantity: 641,
    category: "electronics",
    weight: 19.91,
    description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    id: 2,
    img: "https://olimpicocol.co/web/wp-content/uploads/2023/12/natalia-linares-1024x683-1.jpeg",
    fecha: "24/05/2024",
  },
  {
    product_name: "Coffee Caramel Biscotti",
    price: 985.32,
    quantity: 14,
    category: "food",
    weight: 66.85,
    description:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
    id: 3,
    img:"https://cdn.semanariolacalle.com/2024/07/Natalia-Linares-orgullo-del-Cesar-en-los-Olimpicos.jpg",
    fecha: "24/05/2024",
  },
  {
    product_name: "Soho Lychee Liqueur",
    price: 606.73,
    quantity: 654,
    category: "food",
    weight: 51.08,
    description:
      "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    id: 4,
    img: "https://cdn.semanariolacalle.com/2022/07/00B898F7-219D-43D6-9951-2035FCFD12D2.jpeg",
  },
  {
    product_name: "Beets - Mini Golden",
    price: 39.46,
    quantity: 609,
    category: "electronics",
    weight: 19.97,
    description:
      "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    id: 5,
    img: "https://www.diariodelcesar.com/wp-content/uploads/2019/08/EN-EL-CAMPEONATO-1.jpg",
  },
  {
    product_name: "Paper - Brown Paper Mini Cups",
    price: 784.06,
    quantity: 328,
    category: "clothing",
    weight: 99.31,
    description:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    id: 6,
    img: "https://cdn.semanariolacalle.com/2021/08/82E3E766.21.54-p.m..png",
  },
  {
    product_name: "Icecream - Dstk Strw Chseck",
    price: 462.19,
    quantity: 952,
    category: "food",
    weight: 52.64,
    description:
      "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    id: 7,
    img: "https://portalenlace.com.co/wp-content/uploads/2022/08/atletismo.jpeg",
  },
  {
    product_name: "Yogurt - Banana, 175 Gr",
    price: 749.11,
    quantity: 797,
    category: "food",
    weight: 21.32,
    description:
      "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    id: 8,
    img: "https://pbs.twimg.com/media/F2xlxieW4AAeVLN.jpg:large",
  },
  {
    product_name: "Fish - Atlantic Salmon, Cold",
    price: 238.66,
    quantity: 498,
    category: "clothing",
    weight: 30.7,
    description:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    id: 9,
    img: "https://files.antena2.com/antena2/public/styles/imagen_despliegue/public/2022-07/Natalia%20Linares%20-%20Atletismo%20-%20Colombia.jpg.webp?VersionId=smGVELfsSGkHyYmhxqlmFiXxF5Mbue6a&itok=ShaqxPev",
  },
  {
    product_name: "Durian Fruit",
    price: 591.87,
    quantity: 577,
    category: "food",
    weight: 93.09,
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    id: 10,
    img: "https://estaticos.elcolombiano.com/binrepository/780x700/1c0/780d565/none/11101/LLSK/cupoolimpico_44927032_20240421092155.jpg",
  },
];
